const env = {
  SIP_SERVER: process.env.REACT_APP_SIP_SERVER,
  AUTHORIZATION_USER: process.env.REACT_APP_AUTHORIZATION_USER,
  AUTHORIZATION_PASSWORD: process.env.REACT_APP_AUTHORIZATION_PASSWORD,
  DISPLAY_NAME: process.env.REACT_APP_DISPLAY_NAME,
  USER_AGENT: process.env.REACT_APP_USER_AGENT,
  STUN_SERVERS: process.env.REACT_APP_STUN_SERVERS,
  LOG_LEVEL: process.env.REACT_APP_LOG_LEVEL,
  AVATAR: process.env.REACT_APP_AVATAR,
  NUMBER: process.env.REACT_APP_NUMBER,
};

export default env;
